# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('userNo', models.IntegerField(primary_key=True, serialize=False)),
                ('userPasswd', models.TextField()),
            ],
        ),
    ]
